### PR TITLE
Update to windows-rs 0.48

### PR DESCRIPTION
**Pull request by aznhe21**
I don't know if this is the correct procedure, especially around a winmd file, but the sample worked.

### CODE REVIEW

**Comment by aznhe21** [comment]
It seems that the winmd file does not need to be updated, so I deleted the second commit.

**Comment by wravery** [comment]
Looks like there's a conflict with some of the new interface implementations I just added in `options.rs`. Feel free to update them, or I can take a deeper look in a little while.

**Comment by wravery** [comment]
Once this is merged, I'll bump the version numbers and publish the changes in all 3 crates to crates.io.

**Comment by aznhe21** [comment]
OK, I'll do that. Just a moment, please.

**Comment by aznhe21** [comment]
done.

**Review by wravery — APPROVED** [review]

**Pull request merged**
